/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import static basiclibrary.Library.analyzeWeathData;
import static basiclibrary.Library.tally;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

public class LibraryTest {



    @Test
    void analyzeWeathDataTest() {

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        String rightResult = "Low Temperature 51" +
                "\nHigh Temperature 72" +
                "\nNever saw temperature: 63" +
                "\nNever saw temperature: 67" +
                "\nNever saw temperature: 68" +
                "\nNever saw temperature: 69";
           assertEquals(rightResult,analyzeWeathData(weeklyMonthTemperatures));
    }
       @Test
       public void tallyTest(){
           String out="Bush";
           List<String> votes = new ArrayList<>();
           votes.add("Bush");
           votes.add("Bush");
           votes.add("Bush");
           votes.add("Shrub");
           votes.add("Hedge");
           votes.add("Shrub");
           votes.add("Bush");
           votes.add("Hedge");
           votes.add("Bush");

          assertEquals(out,tally(votes));

    }
}
