/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.*;

public class Library {
    public static void main(String[] args) {
        String welcomeMsg = "Welcome To Lab 2 Solution";
        int[] newArray = {4, 2, 5, 7, 9, 4, 1};
        System.out.println(welcomeMsg);
        roll(4);
        containsDuplicates(newArray);
        Averages(newArray);
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        ArrOfArr(weeklyMonthTemperatures);

    }

    public static ArrayList roll(int n) {
        System.out.println(" roll  Function output:************");
        Random random = new Random();
        int max = 6;
        int min = 1;
        ArrayList<Integer> myArray = new ArrayList<Integer>();
        for (int i = 0; i < n; i++) {
            myArray.add(random.nextInt(max - min + 1) + min);
        }
        System.out.println(myArray);
        return myArray;
    }

    public static boolean containsDuplicates(int[] duplicateArray) {
        System.out.println("containsDuplicates  Function output..........");
        for (int i = 0; i < duplicateArray.length; i++) {
            for (int j = 0; j < duplicateArray.length; j++) {
                if (i != j) {
                    if (duplicateArray[i] == duplicateArray[j]) {
                        System.out.println("true");
                        return true;
                    }
                }
            }
        }
        System.out.println("false");
        return false;
    }

    public static double Averages(int[] newArray) {
        System.out.println(" Averages  Function output..........");
        System.out.println("Array:" + Arrays.toString(newArray));
        int sum = 0;
        for (int i = 0; i < newArray.length; i++) {
            sum += newArray[i];
        }
       double avg =  (double)sum / (newArray.length);
        System.out.println("Average = " + avg);
        return avg;
    }

    public static int[] ArrOfArr(int[][] arr ){
        int [] array= arr[0];
        for (int i = 0; i <arr.length ; i++) {
            if(Averages(arr[i])<Averages(array)){
                array=arr[i];
            }
        }
        System.out.println(Arrays.toString(array));
        return array;
    }

}
