/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {

    public static void main(String[] args) {
       Restaurant newRes = new Restaurant("shatha",7);
        newRes.addReview("shatha",4);
        System.out.println(newRes);

    }


}
