/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package linter;



import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.nio.file.Paths;


import static linter.App.linter;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class AppTest {

    @Test
    public void testCheckLine() {
        Path p = Paths.get("src/main/resources/test.js");



        String expect = "Line 3 Missing semicolon.\n" ;




        assertEquals( expect, linter(p));
    }

}